name: Build & Deploy Engine
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            targetos: win32
            targetarch: amd64
          - os: windows-2022
            targetos: win32
            targetarch: i386

    env:
      SDL_VERSION: 2.32.10
      FFMPEG_VERSION: 7.1
      GH_CPU_ARCH: ${{ matrix.targetarch }}
      GH_CPU_OS: ${{ matrix.targetos }}
      GH_CROSSCOMPILING: false

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: bash scripts/gha/deps_win32.sh

    - name: Build engine
      env:
        FWGS_PFX_PASSWORD: ${{ secrets.FWGS_PFX_PASSWORD }}
      run: bash scripts/gha/build_win32.sh

    - name: Upload engine (artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: artifact-win32-${{ matrix.targetarch }}
        path: artifacts/*
